const MISSING_NARVAR_ORDER_STRING = 'No Order Information found for Order Number'

const NARVAR_ORDER_LAST_MODIFIED = 'orderLastModifiedDate'
const NARVAR_ORDER_ITEM_LAST_MODIFIED = 'orderItemLastModifiedDate'

const JESTA_LANGUAGE_NUMBERS_TO_LOCALES = {
  '1': 'en-CA',
  '3': 'fr-CA'
}

const JESTA_STATUSES_TO_NARVAR_STATUSES = {
  'SHIPPED': 'SHIPPED',
  'OPEN': 'NOT_SHIPPED',
  'IN PICKING': 'PROCESSING',
  'CANCELLED': 'CANCELLED',
  'PICKUP': 'READY_FOR_PICKUP',
  'PICKEDUP': 'PICKED_UP'
}

const LOCALE_TO_PRODUCT = {
  'en-CA': 'product',
  'fr-CA': 'produit'
}

const NARVAR_FULFILLMENT_TYPES = {
  HOME_DELIVERY: 'HD',
  BOPIS: 'BOPIS',
  BOSS: 'BOSS'
}

module.exports = {
  JESTA_LANGUAGE_NUMBERS_TO_LOCALES,
  LOCALE_TO_PRODUCT,
  JESTA_STATUSES_TO_NARVAR_STATUSES,
  MISSING_NARVAR_ORDER_STRING,
  NARVAR_ORDER_LAST_MODIFIED,
  NARVAR_ORDER_ITEM_LAST_MODIFIED,
  NARVAR_FULFILLMENT_TYPES
}
