const MISSING_NARVAR_ORDER_STRING = 'No Order Information found for Order Number'

const NARVAR_ORDER_LAST_MODIFIED = 'orderLastModifiedDate'
const NARVAR_ORDER_ITEM_LAST_MODIFIED = 'orderItemLastModifiedDate'
const NARVAR_SHIPMENT_LAST_MODIFIED = 'shipmentLastModifiedDate'
const NARVAR_SHIPMENT_ITEM_LAST_MODIFIED = 'shipmentItemLastModifiedDate'

const JESTA_LANGUAGE_NUMBERS_TO_LOCALES = {
  '1': 'en-CA',
  '3': 'fr-CA'
}

const JESTA_STATUSES_TO_NARVAR_STATUSES = {
  'SHIPPED': 'SHIPPED',
  'OPEN': 'NOT_SHIPPED',
  'IN PICKING': 'PROCESSING',
  'CANCELLED': 'CANCELLED',
  'PICKUP': 'READY_FOR_PICKUP',
  'PICKEDUP': 'PICKED_UP'
}

const LOCALE_TO_PRODUCT = {
  'en-CA': 'product',
  'fr-CA': 'produit'
}

const NARVAR_FULFILLMENT_TYPES = {
  HOME_DELIVERY: 'HD',
  BOPIS: 'BOPIS',
  BOSS: 'BOSS'
}

const JESTA_CARRIER_ID_TO_NARVAR_CARRIER_ID = {
  FDX: 'fedex',
  CP: 'canadapost'
}

const JESTA_SERVICE_TYPES_TO_NARVAR_SERVICE_TYPES = {
  FDX: {
    EXPRESS: 'E1AM',
    GROUND: 'FG',
    ECONOMY: 'IE',
    STANDARD_OVERNIGHT: 'E1'
  },
  CP: {
    'EXPEDITED PARCEL': 'EP',
    XPRESSPOST: 'E2',
  }
}

module.exports = {
  JESTA_LANGUAGE_NUMBERS_TO_LOCALES,
  LOCALE_TO_PRODUCT,
  JESTA_STATUSES_TO_NARVAR_STATUSES,
  MISSING_NARVAR_ORDER_STRING,
  NARVAR_ORDER_LAST_MODIFIED,
  NARVAR_ORDER_ITEM_LAST_MODIFIED,
  NARVAR_FULFILLMENT_TYPES,
  JESTA_CARRIER_ID_TO_NARVAR_CARRIER_ID,
  JESTA_SERVICE_TYPES_TO_NARVAR_SERVICE_TYPES,
  NARVAR_SHIPMENT_LAST_MODIFIED,
  NARVAR_SHIPMENT_ITEM_LAST_MODIFIED
}
