const JESTA_LANGUAGE_NUMBERS_TO_LOCALES = {
  '1': 'en-CA',
  '3': 'fr-CA'
}

const JESTA_STATUSES_TO_NARVAR_STATUSES = {
  'SHIPPED': 'SHIPPED',
  'OPEN': 'NOT_SHIPPED',
  'IN PICKING': 'PROCESSING',
  'CANCELLED': 'CANCELLED',
  'PICKUP': 'READY_FOR_PICKUP',
  'PICKEDUP': 'PICKED_UP'
}

const LOCALE_TO_PRODUCT = {
  'en-CA': 'product',
  'fr-CA': 'produit'
}

module.exports = {
  JESTA_LANGUAGE_NUMBERS_TO_LOCALES,
  LOCALE_TO_PRODUCT,
  JESTA_STATUSES_TO_NARVAR_STATUSES
}
