apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: add-static-routes-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: add-static-routes-role
subjects:
- kind: ServiceAccount
  name: add-static-routes
  namespace: default
