apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
spec:
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect-host
          image: us.icr.io/hrretailplatform/kafkaconnecthost:latest
          ports:
            - containerPort: 28083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_BOOTSTRAP_SERVERS
            - name: CONNECT_REST_PORT
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_REST_PORT
            - name: CONNECT_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_GROUP_ID
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_CONFIG_STORAGE_TOPIC
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_OFFSET_STORAGE_TOPIC
            - name: CONNECT_STATUS_STORAGE_TOPIC
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_STATUS_STORAGE_TOPIC
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
            - name: CONNECT_KEY_CONVERTER
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_KEY_CONVERTER
            - name: CONNECT_VALUE_CONVERTER
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_VALUE_CONVERTER
            - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_INTERNAL_KEY_CONVERTER
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_INTERNAL_VALUE_CONVERTER
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_REST_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_LOG4J_ROOT_LOGLEVEL
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_LOG4J_ROOT_LOGLEVEL
            - name: CONNECT_PLUGIN_PATH
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PLUGIN_PATH
            - name: CONNECT_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key:  CONNECT_SASL_JAAS_CONFIG
            - name: CONNECT_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_SECURITY_PROTOCOL
            - name: CONNECT_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_SASL_MECHANISM
            - name: CONNECT_SSL_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_SSL_PROTOCOL
            - name: CONNECT_SSL_ENABLED_PROTOCOLS
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_SSL_ENABLED_PROTOCOLS
            - name: CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
            - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PRODUCER_SASL_JAAS_CONFIG
            - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PRODUCER_SECURITY_PROTOCOL
            - name: CONNECT_PRODUCER_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PRODUCER_SASL_MECHANISM
            - name: CONNECT_PRODUCER_SSL_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PRODUCER_SSL_PROTOCOL
            - name: CONNECT_PRODUCER_SSL_ENABLED_PROTOCOLS
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PRODUCER_SSL_ENABLED_PROTOCOLS
            - name: CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: eventstreams-kafka-connect
                  key: CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
