apiVersion: v1
kind: Service
metadata:
  name: mynodeportservice
  labels:
    app: kafka-connect
spec:
  selector:
    app: kafka-connect
  type: NodePort
  ports:
   - port: 28083
     nodePort: 31514
