. .env

if [ $1 = "prod" ]; then
  KAFKA_USERNAME=$KAFKA_USER_PROD
  KAFKA_PASSWORD=$KAFKA_PASSWORD_PROD
  KAFKA_BROKERS=$KAFKA_BROKERS_PROD
elif  [ $1 = "dev" ]; then
  KAFKA_USERNAME=$KAFKA_USER_DEV
  KAFKA_PASSWORD=$KAFKA_PASSWORD_DEV
  KAFKA_BROKERS=$KAFKA_BROKERS_DEV
elif  [ $1 = "stage" ]; then
  KAFKA_USERNAME=$KAFKA_USER_STAGE
  KAFKA_PASSWORD=$KAFKA_PASSWORD_STAGE
  KAFKA_BROKERS=$KAFKA_BROKERS_STAGE
elif  [ $1 = "development" ]; then
  KAFKA_USERNAME=$KAFKA_USER_DEVELOPMENT
  KAFKA_PASSWORD=$KAFKA_PASSWORD_DEVELOPMENT
  KAFKA_BROKERS=$KAFKA_BROKERS_DEVELOPMENT
else
  echo "No environment provided"
  exit 1
fi
