apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-standard
  labels:
    app: kafka-connect-standard
spec:
  selector:
    app: kafka-connect-standard
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 28083
