# Created by running 'kubectl convert -f ./kafka-connect-deployment.yaml --output-version apps/v1 > kafka-connect-deployment-apiVersion-appsv1.yaml'
# More info: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-connect-standard
  name: kafka-connect-standard
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kafka-connect-standard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-connect-standard
    spec:
      containers:
      - env:
        # either KAFKA_OPTS or JAVA_OPTS set the timezone on Kafka Connect, I'm not sure which.
        # I'm also not sure whether it is -Doracle.jdbc.timezoneAsRegion=false or -Duser.timezone=UTC.
        # We should try KAFKA_OPTS with -Doracle.jdbc.timezoneAsRegion=false and if it works, get rid of the rest.
        - name: KAFKA_OPTS
          value: "-Doracle.jdbc.timezoneAsRegion=false -Duser.timezone=UTC"
        - name: JAVA_OPTS
          value: "-Doracle.jdbc.timezoneAsRegion=false -Duser.timezone=UTC"
        - name: CONNECT_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              key: CONNECT_BOOTSTRAP_SERVERS
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_REST_PORT
          valueFrom:
            secretKeyRef:
              key: CONNECT_REST_PORT
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_GROUP_ID
          valueFrom:
            secretKeyRef:
              key: CONNECT_GROUP_ID
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          valueFrom:
            secretKeyRef:
              key: CONNECT_CONFIG_STORAGE_TOPIC
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          valueFrom:
            secretKeyRef:
              key: CONNECT_OFFSET_STORAGE_TOPIC
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_STATUS_STORAGE_TOPIC
          valueFrom:
            secretKeyRef:
              key: CONNECT_STATUS_STORAGE_TOPIC
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          valueFrom:
            secretKeyRef:
              key: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          valueFrom:
            secretKeyRef:
              key: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          valueFrom:
            secretKeyRef:
              key: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_KEY_CONVERTER
          valueFrom:
            secretKeyRef:
              key: CONNECT_KEY_CONVERTER
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_VALUE_CONVERTER
          valueFrom:
            secretKeyRef:
              key: CONNECT_VALUE_CONVERTER
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          valueFrom:
            secretKeyRef:
              key: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          valueFrom:
            secretKeyRef:
              key: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          valueFrom:
            secretKeyRef:
              key: CONNECT_INTERNAL_KEY_CONVERTER
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          valueFrom:
            secretKeyRef:
              key: CONNECT_INTERNAL_VALUE_CONVERTER
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONNECT_REST_HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          valueFrom:
            secretKeyRef:
              key: CONNECT_LOG4J_ROOT_LOGLEVEL
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PLUGIN_PATH
          valueFrom:
            secretKeyRef:
              key: CONNECT_PLUGIN_PATH
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              key: CONNECT_SASL_JAAS_CONFIG
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_SECURITY_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: CONNECT_SECURITY_PROTOCOL
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_SASL_MECHANISM
          valueFrom:
            secretKeyRef:
              key: CONNECT_SASL_MECHANISM
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_SSL_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: CONNECT_SSL_PROTOCOL
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_SSL_ENABLED_PROTOCOLS
          valueFrom:
            secretKeyRef:
              key: CONNECT_SSL_ENABLED_PROTOCOLS
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          valueFrom:
            secretKeyRef:
              key: CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              key: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: CONNECT_PRODUCER_SECURITY_PROTOCOL
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PRODUCER_SASL_MECHANISM
          valueFrom:
            secretKeyRef:
              key: CONNECT_PRODUCER_SASL_MECHANISM
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PRODUCER_SSL_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: CONNECT_PRODUCER_SSL_PROTOCOL
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PRODUCER_SSL_ENABLED_PROTOCOLS
          valueFrom:
            secretKeyRef:
              key: CONNECT_PRODUCER_SSL_ENABLED_PROTOCOLS
              name: eventstreams-kafka-connect-standard
        - name: CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          valueFrom:
            secretKeyRef:
              key: CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              name: eventstreams-kafka-connect-standard
        image: us.icr.io/hrretailplatform/kafkaconnecthost:5.3.3
        imagePullPolicy: IfNotPresent
        name: kafka-connect-standard-host
        ports:
        - containerPort: 28083
          protocol: TCP
        resources:
          limits:
            cpu: 3000m
            memory: 8Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
