if [ $1 = "inv" ]; then
  CONNECTOR_FILE_NAME="skuinventory-jdbc-source.json"
elif  [ $1 = "invea" ]; then
  CONNECTOR_FILE_NAME="skuinventory-endlessaisle-jdbc-source.json"
elif  [ $1 = "returndetailsbulk" ]; then
  CONNECTOR_FILE_NAME="return-details-jdbc-source-bulk.json"
elif  [ $1 = "returndetailsrecovery" ]; then
  CONNECTOR_FILE_NAME="return-details-jdbc-source-recovery.json"
elif  [ $1 = "returndetails" ]; then
  CONNECTOR_FILE_NAME="return-details-jdbc-source.json"
elif  [ $1 = "stylescreate" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-create-jdbc-source.json"
elif  [ $1 = "stylesupdaterecovery" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-update-jdbc-source-recovery.json"
elif  [ $1 = "stylesupdate" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-update-jdbc-source.json"
elif  [ $1 = "stylecoloursupdate" ]; then
  CONNECTOR_FILE_NAME="elcat-stylecolours-update-jdbc-source.json"
elif  [ $1 = "salepricesrecovery" ]; then
  CONNECTOR_FILE_NAME="sale-prices-jdbc-source-recovery.json"
elif  [ $1 = "stylebasic" ]; then
  CONNECTOR_FILE_NAME="style-basic-jdbc-source.json"
elif  [ $1 = "saleprices" ]; then
  CONNECTOR_FILE_NAME="sale-prices-jdbc-source.json"
elif  [ $1 = "shipmentsupdate" ]; then
  CONNECTOR_FILE_NAME="shipments-update-jdbc-source.json"
elif  [ $1 = "shipmentscreate" ]; then
  CONNECTOR_FILE_NAME="shipments-create-jdbc-source.json"
elif  [ $1 = "shipmentdetailsupdate" ]; then
  CONNECTOR_FILE_NAME="shipment-details-update-jdbc-source.json"
elif  [ $1 = "shipmentdetailscreate" ]; then
  CONNECTOR_FILE_NAME="shipment-details-create-jdbc-source.json"
elif  [ $1 = "salesorderdetailsupdate" ]; then
  CONNECTOR_FILE_NAME="sales-order-details-update-jdbc-source.json"
elif  [ $1 = "salesorderdetailscreate" ]; then
  CONNECTOR_FILE_NAME="sales-order-details-create-jdbc-source.json"
elif  [ $1 = "salesordersupdate" ]; then
  CONNECTOR_FILE_NAME="sales-orders-update-jdbc-source.json"
elif  [ $1 = "salesorderscreate" ]; then
  CONNECTOR_FILE_NAME="sales-orders-create-jdbc-source.json"
elif  [ $1 = "skus" ]; then
  CONNECTOR_FILE_NAME="skus-jdbc-source.json"
elif  [ $1 = "instoreprices" ]; then
  CONNECTOR_FILE_NAME="in-store-prices-jdbc-source.json"
elif  [ $1 = "storesfulfill" ]; then
  CONNECTOR_FILE_NAME="stores-fulfill-jdbc-source.json"
elif  [ $1 = "thresholds" ]; then
  CONNECTOR_FILE_NAME="thresholds-jdbc-source.json"
elif  [ $1 = "onlineprices" ]; then
  CONNECTOR_FILE_NAME="online-prices-jdbc-source.json"
elif  [ $1 = "dep27fulfill" ]; then
  CONNECTOR_FILE_NAME="stores-dep27fulfill-jdbc-source.json"
elif  [ $1 = "barcodes" ]; then
  CONNECTOR_FILE_NAME="barcodes-jdbc-source.json"
elif  [ $1 = "stores" ]; then
  CONNECTOR_FILE_NAME="stores-jdbc-source.json"
elif  [ $1 = "invbulk" ]; then
  CONNECTOR_FILE_NAME="skuinventory-jdbc-source-bulk.json"
elif  [ $1 = "invbindingtest" ]; then
  CONNECTOR_FILE_NAME="skuinventory-jdbc-source-bindingtest.json"
elif  [ $1 = "invfast" ]; then
  CONNECTOR_FILE_NAME="inventory-fast-load-jdbc.json"
elif  [ $1 = "facets" ]; then
  CONNECTOR_FILE_NAME="facets-jdbc-source.json"
elif  [ $1 = "fail" ]; then
  CONNECTOR_FILE_NAME="failing-connector-test.json"
elif  [ $1 = "stylesold" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-jdbc-source-old.json"
elif  [ $1 = "stylesnew" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-jdbc-source_new.json"
elif  [ $1 = "styles" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-jdbc-source.json"
elif  [ $1 = "stylesaudit" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-audit-jdbc-source.json"
elif  [ $1 = "stylesauditrecovery" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-audit-jdbc-source-recovery.json"
elif  [ $1 = "stylesauditold" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-audit-jdbc-source-old.json"
elif  [ $1 = "stylesspecial" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-audit-jdbc-source-special.json"
elif  [ $1 = "stylesauditnew" ]; then
  CONNECTOR_FILE_NAME="elcat-catalog-audit-jdbc-source_new.json"
elif  [ $1 = "medias" ]; then
  CONNECTOR_FILE_NAME="medias-jdbc-source.json"
elif  [ $1 = "mediacontainers" ]; then
  CONNECTOR_FILE_NAME="media-containers-jdbc-source.json"
else
  echo "Invalid connector type" 
  exit 1
fi
