. .env

if [ $1 = "prod" ]; then
  KUBE_USERNAME=$KUBE_PROD_USERNAME
  KUBE_PASSWORD=$KUBE_PROD_PASSWORD 
  KUBE_TENANT=$KUBE_PROD_TENANT
  KUBE_HOST=$KUBE_PROD_HOST
elif  [ $1 = "stage" ]; then
  KUBE_USERNAME=$KUBE_STAGE_USERNAME
  KUBE_PASSWORD=$KUBE_STAGE_PASSWORD 
  KUBE_TENANT=$KUBE_STAGE_TENANT
  KUBE_HOST=$KUBE_STAGE_HOST
elif  [ $1 = "dev" ]; then
  KUBE_USERNAME=$KUBE_DEV_USERNAME
  KUBE_PASSWORD=$KUBE_DEV_PASSWORD 
  KUBE_TENANT=$KUBE_DEV_TENANT
  KUBE_HOST=$KUBE_DEV_HOST
elif  [ $1 = "development" ]; then
  KUBE_USERNAME=$KUBE_DEVELOPMENT_USERNAME
  KUBE_PASSWORD=$KUBE_DEVELOPMENT_PASSWORD 
  KUBE_TENANT=$KUBE_DEVELOPMENT_TENANT
  KUBE_HOST=$KUBE_DEVELOPMENT_HOST
else
  echo "No environment provided"
  exit 1
fi
