. .env

if [ $1 = "prod" ]; then
  KUBE_USERNAME=$KUBE_PROD_USERNAME
  KUBE_PASSWORD=$KUBE_PROD_PASSWORD 
  KUBE_TENANT=$KUBE_PROD_TENANT
  KUBE_HOST=$KUBE_PROD_HOST
elif  [ $1 = "dev" ]; then
  KUBE_USERNAME=$KUBE_DEV_USERNAME
  KUBE_PASSWORD=$KUBE_DEV_PASSWORD 
  KUBE_TENANT=$KUBE_DEV_TENANT
  KUBE_HOST=$KUBE_DEV_HOST
else
  echo "No environment provided"
  exit 1
fi
